### ISSUE TITLE
Add Image-URL Function to Sass Directory

### ISSUE THREAD

**Issue by dennisgaebel** [luminusmedia/lwbp#10]
This function acts the same as Compass' famous ``img-url`` helper except it compiles with libsass and has no need for Compass. This should be added to the functions folder of the scss directory called “``_img-url.scss``”

```scss
@function img-url($url) {
  @return url("#{$img-dir}#{$url}");
}
```

Example Code:

```scss
$img-dir: "images/" !default;

.el {
  background: img-url('picture.jpg') top left no-repeat;
}
```
