### ISSUE TITLE
Styling Broken Images

### ISSUE THREAD

**Issue by dennisgaebel** [luminusmedia/lwbp#11]
Referenced Article [http://bitsofco.de/styling-broken-images](http://bitsofco.de/styling-broken-images)

```scss
img:before {  
  content: " ";
  display: block;
  position: absolute;
  top: -10px;
  left: 0;
  height: calc(100% + 10px);
  width: 100%;
  background-color: rgb(230, 230, 230);
  border: 2px dotted rgb(200, 200, 200);
}

img:after {  
  content: "Broken Image of " attr(alt);
  display: block;
  position: absolute;
  top: 5px;
  left: 0;
  width: 100%;
  text-align: center;
}
```
