### ISSUE TITLE
Add Font Loader Mixin

### ISSUE THREAD

**Issue by dennisgaebel** [luminusmedia/lwbp#24]
```scss
@mixin font-loader($weight, $family…) {
  .wf-active &,
  .wf-inactive & {
    font-family: #{$family…};
    font-weight: $weight;
  }

  .wf-active &,
  .wf-inactive &,
  .no-js & {
    visibility: visible;
  }
}

// @example
@include font-loader(400, '"source-sans-pro", sans-serif');
```
