### ISSUE TITLE
Select Menu

### ISSUE THREAD

**Issue by dennisgaebel** [luminusmedia/lwbp#31]
Just for the places that cannot show a custom indicator…

```scss
select {
  @media screen and (-webkit-min-device-pixel-ratio:0) {
    background-image: url(./img/svgsprite/arrow-down.svg);
    background-position: right ($spacing * 2) top 50%;
    background-repeat: no-repeat;
    background-size: 20px 20px;
  }
}
```
